DROP TABLE IF EXISTS user CASCADE;

CREATE TABLE user(
	id INT AUTO_INCREMENT,
	firstname VARCHAR(30) NOT NULL,
	last_name VARCHAR(30) NOT NULL,
	username VARCHAR(30) UNIQUE NOT NULL,
	age INT NOT NULL, 
	PRIMARY KEY(id)
);